[meta]
name = "English"
author = "R1DF"
description = "The pre-installed English language file."

[linked]
userTemplateFile = "user_lang_en.txt"
templateOffset = 29

[reusable]
yes = "Yes"
no = "No"

connectingToAPIAwaiter = "Connecting to the Scratch API..."
collectingDataAwaiter = "Collecting request data..."
success = "Success."

enterToContinue = "Press Enter to continue."
enterToExit = "Press Enter to exit."
months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

[tests]
testingConnection = "Testing internet connection..."
requestData = "Request data:"
internetConnectionSuccess = "Connection successful."
internetConnectionFailure = "Connection failed!\nPlease check your internet connection."

[introduction]
welcome = "Welcome to Scratchgetter v1.0.0., written by R1DF."
legalNotice = "All data is legally obtained by the Scratch API."
optionsQuery = "Select what you would like to do:"
options = [
    "Get user information (requires username)",
    "Get project information (requires project ID)",
    "Get studio information (requires studio ID)",
    "Change language",
    "Quit"
]

[get_user]
# Queries
enterUsernameQuery = "Enter username:"
enterFileFolderQuery = "Enter file folder (Tab for hints) :"
enterFileNameQuery = "Enter file name:"
saveFileQuery = "Save the text file?"


# Awaiters
loadingSTStatusAwaiter = "Checking ST status..."
loadingJoinDateAwaiter = "Loading join date..."
loadingIDAwaiter = "Loading ID..."
loadingProfileContentsAwaiter = "Loading profile contents..."
loadingAboutMeAwaiter = "Loading \"About Me\" section..."
loadingWIWOAwaiter = "Loading \"What I'm Working On\" section..."
loadingCountryAwaiter = "Loading country..."
loadingPFPLinksAwaiter = "loading profile picture links..."

# Template Replacers
isSTReplacer = "The user is a member of the Scratch Team."
notSTReplacer = "The user is not a member of the Scratch Team."
hasAboutMeReplacer = "About Me"
noAboutMeReplacer = "The user's \"About Me\" section is empty."
hasWIWOReplacer = "What I'm Working On"
noWIWOReplacer = "The user's \"What I'm Working On\" section is empty."

# Other text
user = "User:"
userObtained = "User obtained."
imageAvailability = "Links to images for the profile pictures are accessible in a text file."
PFPLinks = "Profile picture links:"