[meta]
name = "English"
file_name = "lang_en.toml"
author = "R1DF"
description = "The pre-installed English language file."
for_version = "1.0.0"

[linked]
dateFormatterFile = "date_formatters.df_lang_en"

[reusable]
yes = "Yes"
no = "No"
cancel = "Cancel"

connectingToAPIAwaiter = "Connecting to the Scratch API..."
collectingDataAwaiter = "Collecting request data..."
error = "Error!"
success = "Success."

enterToContinue = "Press Enter to continue."
enterToExit = "Press Enter to exit."

monthsFormatted = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

[tests]
testingConnection = "Testing internet connection..."
requestData = "Request data:"
internetConnectionSuccess = "Connection successful."
internetConnectionFailure = "Connection failed!\nPlease check your internet connection."

[templates]
user = """
USERNAME's user contents:
IS_ST

Join date and time: DATETIME
Location: COUNTRY
User ID: USER_ID
Profile ID: PROFILE_ID

ABOUT_ME

WIWO

API response link: https://api.scratch.mit.edu/users/USERNAME/\
"""

project = """
Project contents:
ID: PROJECT_ID
IS_VISIBLE
IS_REMIX

Title: \"TITLE\"
Author: AUTHOR
Token: PROJECT_TOKEN
Created on DATE_CREATED
Last edit on DATE_LAST_EDITED
Published on DATE_PUBLISHED

VIEWS views
LOVES loves
FAVOURITES favourites
REMIXES remixes

INSTRUCTIONS

DESCRIPTION

HAS_COMMENTS


API response link: https//api.scratch.mit.edu/projects/PROJECT_ID/
\
"""

[introduction]
welcome = "Welcome to Scratchgetter v1.0.0., written by R1DF."
legalNotice = "All data is legally obtained by the Scratch API."
optionsQuery = "Select what you would like to do:"
options = [
    "Get user information (requires username)", # 0
    "Get project information (requires project ID)", # 1
    "Get studio information (requires studio ID)", # 2
    "Change language", # 3
    "Quit" # 4
]

[get_user]
# Queries
enterUsernameQuery = "Enter username:"
enterFileFolderQuery = "Enter file folder (Press Tab for hints) :"
enterFileNameQuery = "Enter file name:"
saveFileQuery = "Save the text file?"

# Awaiters
loadingSTStatusAwaiter = "Checking ST status..."
loadingJoinDateAwaiter = "Loading join date..."
loadingIDAwaiter = "Loading ID..."
loadingProfileContentsAwaiter = "Loading profile contents..."
loadingAboutMeAwaiter = "Loading \"About Me\" section..."
loadingWIWOAwaiter = "Loading \"What I'm Working On\" section..."
loadingCountryAwaiter = "Loading country..."
loadingPFPLinksAwaiter = "loading profile picture links..."

# Template Replacers
isSTReplacer = "The user is a member of the Scratch Team."
notSTReplacer = "The user is not a member of the Scratch Team."
hasAboutMeReplacer = "About Me"
noAboutMeReplacer = "The user's \"About Me\" section is empty."
hasWIWOReplacer = "What I'm Working On"
noWIWOReplacer = "The user's \"What I'm Working On\" section is empty."

# Other text
user = "User:"
userObtained = "User obtained."
imageAvailability = "Links to images for the profile pictures are accessible in a text file."
PFPLinks = "Profile picture links:"
userInexistent = "The user USERNAME does not exist."

[get_project]
#Queries
enterProjectIDQuery = "Enter project ID:"

# Awaiters
loadingTitleAwaiter = "Loading title..."
loadingVisibilityAwaiter = "Determining if the projet is visible..."
loadingIsRemixAwaiter = "Determining if the project is a remix..."
loadingAuthorAwaiter = "Loading author..."
loadingTokenAwaiter = "Loading project token..."
loadingCreationDateAwaiter = "Loading creation date..."
loadingEditDateAwaiter = "Loading date since last edit..."
loadingPublishDateAwaiter = "Loading date since last published..."
loadingViewsAwaiter = "Loading views..."
loadingLovesAwaiter = "Loading loves..."
loadingFavouritesAwaiter = "Loading favourites..."
loadingRemixesAwaiter = "Loading remixes..."
loadingInstructionsAwaiter = "Loading instructions..."
loadingDescriptionAwaiter = "Loading description..."
loadingHasCommentsAwaiter = "Determining if the project allows commenting..."
loadingThumbnailsAwaiter = "Loading thumbnails..."

# Template Replacers
isRemixReplacer = "The project is a remix. (Parent ID: PARENT_ID; Root ID: ROOT_ID)"
notRemixReplacer = "The project is not a remix."
isVisibleReplacer = "The project is visible."
notVisibleReplacer = "The project is not visible."
hasInstructionsReplacer = "Instructions:"
noInstructionsReplacer = "The project's \"Instructions\" section is empty."
hasDescriptionReplacer = "Description:"
noDescriptionReplacer = "The project's \"Description\" section is empty."
hasCommentsReplacer = "The project allows comments to be added."
noCommentsReplacer = "The project's comments section is closed."

# Other text
projectID = "Project ID:"
projectInexistent = "The project with an ID of PROJECT_ID does not exist."

[language_changing]
introduction = "Change language"
languageListIntroduction = "List of selectable languages:"
ifOne = "You only have one language installed. Please install more to select."
ifZero = "...Not cool. Now you have to reinstall me because I can't function without a valid language file pack."
selectLanguageQuery = "Select language:"
author = "Author:"
description = "Description:"
