[meta]
name = "Ελληνικά"
author = "Άγγελος"
description = "Το προεγκατεστημένο αρχείο της ελληνικής γλώσσας."

[reusable]
enterToContinue = "Πατήστε το πλήκτρο Enter για να συνεχίσετε."
enterToExit = "Πατήστε το πλήκτρο Enter για έξοδο."
months = [
    "Ιανουαρίου",
    "Φεβρουαρίου",
    "Μαρτίου",
    "Απριλίου",
    "Μαΐου",
    "Ιουνίου",
    "Ιουλίου",
    "Αυγούστου",
    "Σεπτεμβρίου",
    "Οκτωβρίου",
    "Νοεμβρίου",
    "Δεκεμβρίου"
]

[tests]
testingConnection = "Τεστ της σύνδεσης στο διαδίκτυο..."
requestData = "Αίτημα δεδομένων:"
internetConnectionSuccess = "Επιτυχής σύνδεση."
internetConnectionFailure = "Αποτυχία σύνδεσης!\nΠαρακαλώ ελέγξτε την σύνδεσή σας στο διαδίκτυο."

[introduction]
welcome = "Καλώς ήρθατε στο Scratchgetter v1.0.0., γραμμένο από τον R1DF."
legalNotice = "Όλα τα δεδομένα συλλέχθηκαν νόμιμα από το Scratch API."
optionsQuery = "Επιλέξτε ένα από τα παρακάτω:"
options = [
    "Λήψη πληροφοριών χρήστη (απαιτείται όνομα χρήστη)",
    "Λήψη πληροφοριών πρότζεκτ (απαιτείται ταυτότητα πρότζεκτ)",
    "Λήψη πληροφοριών στούντιο (απαιτείται ταυτότητα στούντιο)",
    "Αλλαγή γλώσσας",
    "Έξοδος"
]
