[meta]
name = "Ελληνικά"
file_name = "lang_gr.toml"
author = "Άγγελος"
description = "Το προεγκατεστημένο αρχείο της ελληνικής γλώσσας."
for_version = "1.0.0"

[linked]
dateFormatterFile = "date_formatters.df_lang_gr"

[reusable]
# Queries
enterFileFolderQuery = "Εισάγετε τον φάκελο του αρχείου (Πιέστε το πλήκτρο Tab για στοιχεία) :"
enterFileNameQuery = "Πληκτρολογήστε το όνομα του αρχείου:"
saveFileQuery = "Αποθήκευση του γραπτού αρχείου;"

# Other
yes = "ναι"
no = "όχι"
cancel = "Ακύρωση"

connectingToAPIAwaiter = "Σύνδεση με το Scratch API..."
collectingDataAwaiter = "Συλλογή δεδομένων αίτησης..."

success = "Επιτυχία."
error = "Σφάλμα!"

enterToContinue = "Πατήστε το πλήκτρο Enter για να συνεχίσετε."
enterToExit = "Πατήστε το πλήκτρο Enter για έξοδο."

monthsFormatted = [
    "Ιανουαρίου",
    "Φεβρουαρίου",
    "Μαρτίου",
    "Απριλίου",
    "Μαΐου",
    "Ιουνίου",
    "Ιουλίου",
    "Αυγούστου",
    "Σεπτεμβρίου",
    "Οκτωβρίου",
    "Νοεμβρίου",
    "Δεκεμβρίου"
]

[tests]
testingConnection = "Τεστ της σύνδεσης στο διαδίκτυο..."
requestData = "Αίτημα δεδομένων:"
internetConnectionSuccess = "Επιτυχής σύνδεση."
internetConnectionFailure = "Αποτυχία σύνδεσης!\nΠαρακαλώ ελέγξτε την σύνδεσή σας στο διαδίκτυο."

[templates]
user = """
ΜΗΝ ΠΑΡΑΠΟΙΉΣΕΤΕ ΑΥΤΌ ΤΟ ΈΓΓΡΑΦΟ.
Τα περιεχόμενα χρήστη του USERNAME:
IS_ST

Ημερομηνία και ώρα εγγραφής: DATETIME
Περιοχή: COUNTRY
Ταυτότητα χρήστη: USER_ID
Ταυτότητα προφίλ: PROFILE_ID

ABOUT_ME

WIWO

Σύνδεσμος ανταπόκρισης API:
https://api.scratch.mit.edu/users/USERNAME/\
"""

project = """
Περιεχόμενα πρότζεκτ:
Ταυτότητα: PROJECT_ID
IS_REMIX

Τίτλος: \"TITLE\"
Συγγραφέας: AUTHOR
Token: PROJECT_TOKEN
Δημιουργήθηκε στις DATE_CREATED
Τελευταία τροποποίηση στις DATE_LAST_EDITED
Δημοσιεύτηκε στις DATE_PUBLISHED

VIEWS προβολές
LOVES "μου αρέσει"
FAVOURITES αγαπημένα
REMIXES remix

INSTRUCTIONS

DESCRIPTION

HAS_COMMENTS

Σύνδεσμος ανταπόκρισης API: https//api.scratch.mit.edu/projects/PROJECT_ID\
"""

[introduction]
welcome = "Καλώς ήρθατε στο Scratchgetter v1.0.0., γραμμένο από τον R1DF."
legalNotice = "Όλα τα δεδομένα συλλέχθηκαν νόμιμα από το Scratch API."
optionsQuery = "Επιλέξτε ένα από τα παρακάτω:"
options = [
    "Λήψη πληροφοριών χρήστη (απαιτείται όνομα χρήστη)",
    "Λήψη πληροφοριών πρότζεκτ (απαιτείται ταυτότητα πρότζεκτ)",
    "Λήψη πληροφοριών στούντιο (απαιτείται ταυτότητα στούντιο)",
    "Αλλαγή γλώσσας",
    "Έξοδος"
]

[get_user]
# Queries
enterUsernameQuery = "Πληκτρολογήστε το όνομα χρήστη:"

# Awaiters
loadingSTStatusAwaiter = "Έλεγχος ST status..."
loadingJoinDateAwaiter = "Φόρτωση ημερομηνίας εγγραφής..."
loadingIDAwaiter = "Φόρτωση ταυτότητας..."
loadingProfileContentsAwaiter = "Φόρτωση περιεχομένων προφίλ..."
loadingAboutMeAwaiter = "Φόρτωση στήλης \"Σχετικά με εμένα\" ..."
loadingWIWOAwaiter = "Φόρτωση στήλης \"Με τι ασχολούμαι\" ..."
loadingCountryAwaiter = "Φόρτωση χώρας..."
loadingPFPLinksAwaiter = "Φόρτωση συνδέσμου εικόνας προφίλ..."

# Template Replacers
isSTReplacer = "Ο χρήστης είναι μέλος της Scratch Team."
notSTReplacer = "Ο χρήστης δεν είναι μέλος της Scratch Team."
hasAboutMeReplacer = "Σχετικά με εμένα"
noAboutMeReplacer = "Η στήλη \"Σχετικά με εμένα\" του χρήστη είναι άδεια."
hasWIWOReplacer = "Με τι ασχολούμαι"
noWIWOReplacer = "Η στήλη \"Με τι ασχολούμαι\" του χρήστη είναι άδεια."

# Other text
user = "Χρήστης:"
userObtained = "Χρήστης ελήφθη."
imageAvailability = "Οι σύνδεσμοι για τις εικόνες προφίλ είναι προσβάσιμες σε ένα γραπτό αρχείο."
PFPLinks = "Σύνδεσμοι εικόνων προφίλ:"
userInexistent = "Δεν υπάρχει χρήστης USERNAME."

[get_project]
# Queries
enterProjectIDQuery = "Εισάγετε ταυτότητα πρότζεκτ:"

# Awaiters
loadingTitleAwaiter = "Φόρτωση τίτλου..."
loadingVisibilityAwaiter = "Καθορισμός ορατότητας του πρότζεκτ..."
loadingIsRemixAwaiter = "Καθορισμός εάν το πρότζεκτ αποτελεί remix..."
loadingAuthorAwaiter = "Φόρτωση συγγραφέα..."
loadingTokenAwaiter = "Φόρτωση token του πρότζεκτ..."
loadingCreationDateAwaiter = "Φόρτωση ημερομηνίας δημιουργίας..."
loadingEditDateAwaiter = "Φόρτωση ημερομηνίας τελευταίας επεξεργασίας..."
loadingPublishDateAwaiter = "Φόρτωση ημερομηνίας τελευταίας δημοσιοποίησης..."
loadingViewsAwaiter = "Φόρτωση προβολών..."
loadingLovesAwaiter = "Φόρτωση 'μου αρέσει' ..."
loadingFavouritesAwaiter = "Φόρτωση αγαπημένων..."
loadingRemixesAwaiter = "Φόρτωση remix..."
loadingInstructionsAwaiter = "Φόρτωση οδηγιών..."
loadingDescriptionAwaiter = "Φόρτωση περιγραφής..."
loadingHasCommentsAwaiter = "Καθορισμός ρυθμίσεων σχολίων του πρότζεκτ..."
loadingThumbnailsAwaiter = "Φόρτωση thumbnail..."

# Template Replacers
isRemixReplacer = "Το πρότζεκτ αποτελεί remix. (Ταυτότητα αρχικού: PARENT_ID; Ταυτότητα δέντρου: ROOT_ID)"
notRemixReplacer = "Το πρότζεκτ δεν αποτελεί remix."
hasInstructionsReplacer = "Οδηγίες:"
noInstructionsReplacer = "Η στήλη οδηγιών του πρότζεκτ είναι άδεια."
hasDescriptionReplacer = "Περιγραφή:"
noDescriptionReplacer = "Η στήλη περιγραφής του πρότζεκτ είναι άδεια."
hasCommentsReplacer = "Το πρότζεκτ επιτρέπει την προσθήκη σχολίων."
noCommentsReplacer = "Η στήλη σχολίων του πρότζεκτ είναι κλειστή."

# Other text
projectID = "Ταυτότητα πρότζεκτ:"
projectInexistent = "Δεν υπάρχει πρότζεκτ με ταυτότητα PROJECT_ID, ή δεν έχει δημοσιευθεί."
thumbnailAvailability = "Οι σύνδεσμοι για τα εικονίδια του πρότζεκτ είναι προσβάσιμα σε ένα γραπτό αρχείο."
thumbnailLinks = "Εικονίδια:"

[get_studio]
# Queries
enterStudioQuery = "Εισάγετε ταυτότητα στούντιο:"

# Awaiters
loadingTitleAwaiter = "Φόρτωση ονόματος στούντιο..."
loadingHostIDAwaiter = "Φόρτωση ταυτότητας διαχειριστή στούντιο..."
loadingDescriptionAwaiter = "Φόρτωση περιγραφής στούντιο..."
loadingHasCommentsAwaiter = "Έλεγχος κατάστασης σχολίων στούντιο..."
loadingIsOpenAwaiter = "Έλεγχος κατάστασης διαχείρισης πρότζεκτ..."
loadingCommentsAwaiter = "Φόρτωση ποσότητας σχολίων..."
loadingFollowersAwaiter = "Φόρτωση ποσότητας ακολούθων..."
loadingManagersAwaiter = "Φόρτωση ποσότητας διαχειριστών..."
loadingProjectsAwaiter = "Φόρτωση ποσότητας πρότζεκτ..."
loadingCreationDateAwaiter = "Φόρτωση ημερομηνίας δημιουργίας..."
loadingEditDateAwaiter = "Φόρτωση ημερομηνίας τελυταίας τροποποίησης..."
loadingThumbnailAwaiter = "Φόρτωση εικονιδίου στούντιο..."

# Template Replacers
hasDescriptionReplacer = "Περιγραφή:"
noDescriptionReplacer = "Η στήλη περιγραφής του στούντιο είναι άδεια."
hasCommentsReplacer = "Το στούντιο επιτρέπει την προσθήκη σχολίων."
noCommentsReplacer = "Η στήλη σχολίων του στούντιο είναι κλειστή."
allowsAnyProjectsReplacer = "Το στούντιο επιτρέπει την προσθήκη πρότζεκτ από όλα τα μέλη."
forbidsAnyProjectReplacer = "Το στούντιο δεν επιτρέπει την προσθήκη πρότζεκτ από μη-μέλη."

# Other text
studioID = "Ταυτότητα Στούντιο¨"
studioInexistent = "Δεν υπάρχει στούντιο με ταυτότητα στούντιο STUDIO_ID."
thumbnailAvailability = "Ο σύνδεσμος για το εικονίδιο του στούντιο είναι διαθέσιμο σε ένα γραπτό αρχείο."
thumbnailLink = "Σύνδεσμος εικονιδίου (170x100):"

[language_changing]
introduction = "Αλλαγή γλώσσας"
languageListIntroduction = "Λίστα επιλογών γλώσσας:"
ifOne = "Έχετε εγκαταστήσει μόνο μια γλώσσα. Παρακαλώ εγκαταστήστε περισσότερες για να επιλέξετε."
ifZero = "... Μπράβο :( Τώρα πρέπει να εγκαταστήσετε το πρόγραμμα ξανά γιατί δεν μπορεί να λειτουργήσει χωρίς έγκυρο πακέτο αρχείων γλώσσας!"
selectLanguageQuery = "Επιλογή γλώσσας:"
author = "Συγγραφέας:"
description = "Περιγραφή:"
